site_name: Stealth Game Docs
nav:
  - Home: index.md
  - player: player.js.md
  - camera: cam.js.md
  - canvas: canvas.js.md
  - controls: controls.js.md
  - item: item.js.md
  - level: level.js.md
  - player: player.js.md
  - setup: setup.js.md
  - sketch: sketch.js.md



theme: 'material'
